export enum WebhookEvent {
  APPLICATION_STARTUP = "application.startup",
  QRCODE_UPDATED = "qrcode.updated",
  CONNECTION_UPDATE = "connection.update",
  MESSAGES_SET = "messages.set",
  MESSAGES_UPSERT = "messages.upsert",
  MESSAGES_UPDATE = "messages.update",
  MESSAGES_DELETE = "messages.delete",
  SEND_MESSAGE = "send.message",
  CONTACTS_SET = "contacts.set",
  CONTACTS_UPSERT = "contacts.upsert",
  CONTACTS_UPDATE = "contacts.update",
  PRESENCE_UPDATE = "presence.update",
  CHATS_SET = "chats.set",
  CHATS_UPDATE = "chats.update",
  CHATS_UPSERT = "chats.upsert",
  CHATS_DELETE = "chats.delete",
  GROUPS_UPSERT = "groups.upsert",
  GROUPS_UPDATE = "groups.update",
  GROUP_PARTICIPANTS_UPDATE = "group.participants.update",
  NEW_TOKEN = "new.jwt",
}

export enum WebhookEventSetup {
  ApplicationStartup = "APPLICATION_STARTUP",
  QrcodeUpdated = "QRCODE_UPDATED",
  ConnectionUpdate = "CONNECTION_UPDATE",
  MessagesSet = "MESSAGES_SET",
  MessagesUpsert = "MESSAGES_UPSERT",
  MessagesUpdate = "MESSAGES_UPDATE",
  MessagesDelete = "MESSAGES_DELETE",
  SendMessage = "SEND_MESSAGE",
  ContactsSet = "CONTACTS_SET",
  ContactsUpsert = "CONTACTS_UPSERT",
  ContactsUpdate = "CONTACTS_UPDATE",
  PresenceUpdate = "PRESENCE_UPDATE",
  ChatsSet = "CHATS_SET",
  ChatsUpdate = "CHATS_UPDATE",
  ChatsUpsert = "CHATS_UPSERT",
  ChatsDelete = "CHATS_DELETE",
  GroupsUpsert = "GROUPS_UPSERT",
  GroupsUpdate = "GROUPS_UPDATE",
  GroupParticipantsUpdate = "GROUP_PARTICIPANTS_UPDATE",
  NewToken = "NEW_TOKEN",
  MessagesEdited = "MESSAGES_EDITED",
  LabelsEdit = "LABELS_EDIT",
  LabelsAssociation = "LABELS_ASSOCIATION",
  Call = "CALL",
  TypebotStart = "TYPEBOT_START",
  TypebotChangeStatus = "TYPEBOT_CHANGE_STATUS",
  Errors = "ERRORS",
  ErrorsWebhook = "ERRORS_WEBHOOK",
}
